# TCL File Generated by Component Editor 18.1
# Mon Oct 15 08:24:10 GMT-03:00 2018
# DO NOT MODIFY


# 
# LCD_Driver "Driver to LCD" v1.0
#  2018.10.15.08:24:10
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module LCD_Driver
# 
set_module_property DESCRIPTION ""
set_module_property NAME LCD_Driver
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "Driver to LCD"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE false
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 

# 
# parameters
# 


# 
# display items
# 

